### ISSUE TITLE
Can not build in Windows with python3.10

### ISSUE THREAD

**Issue by ouening** [roy-ht/editdistance#75]
When I try to build from source, errors occured:
```
editdistance/_editdistance.cpp(118): error C2059: 语法错误:“if”
editdistance/_editdistance.cpp(119): error C2059: 语法错误:“else”
editdistance/_editdistance.cpp(120): error C2059: 语法错误:“else”
editdistance/_editdistance.cpp(121): error C2059: 语法错误:“else”
editdistance/_editdistance.cpp(122): error C2059: 语法错误:“else”
editdistance/_editdistance.cpp(123): error C2059: 语法错误:“else”
editdistance/_editdistance.cpp(124): error C2059: 语法错误:“else”
editdistance/_editdistance.cpp(125): error C2059: 语法错误:“else”
editdistance/_editdistance.cpp(126): error C2059: 语法错误:“else”
editdistance/_editdistance.cpp(127): error C2059: 语法错误:“else”
editdistance/_editdistance.cpp(128): error C2059: 语法错误:“else”
editdistance/_editdistance.cpp(129): error C2059: 语法错误:“}”
editdistance/_editdistance.cpp(129): error C2143: 语法错误: 缺少“;”(在“}”的前面)
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```
The disscusion in https://github.com/roy-ht/editdistance/pull/50 doesn't help.

**Comment by fenglui** [comment]
me too
